package com.sfb805.udo;

//==============================================================================
//WARNING!!  This file is overwritten by the Block UI Styler while generating
//the automation code. Any modifications to this file will be lost after
//generating the code again.
//
//     Filename:  C:\Users\max\Desktop\NormalDistributedLine.java
//
//      This file was generated by the NX Block UI Styler
//      Created by: max
//            Version: NX 10
//            Date: 03-01-2016  (Format: mm-dd-yyyy)
//            Time: 11:33 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//Purpose:  This TEMPLATE file contains JAVA source to guide you in the
//construction of your Block application dialog. The generation of your
//dialog file (.dlx extension) is the first step towards dialog construction
//within NX.  You must now create a NX Open application that
//utilizes this file (.dlx).
//
//The information in this file provides you with the following:
//
//1.  Help on how to load and display your Block UI Styler dialog in NX
//    using APIs provided in NXOpen.BlockStyler namespace
//2.  The empty callback methods (stubs) associated with your dialog items
//    have also been placed in this file. These empty methods have been
//    created simply to start you along with your coding requirements.
//    The method name, argument list and possible return values have already
//    been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
import java.rmi.RemoteException;
import nxopen.*;
import nxopen.blockstyler.*;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class NormalDistributedLine implements BlockDialog.Initialize, BlockDialog.DialogShown, BlockDialog.Ok, BlockDialog.Update
{
  //class members
  public static Session theSession = null;
  public static UI theUI = null;
  private String theDlxFileName;
  private nxopen.blockstyler.BlockDialog theDialog;
  private nxopen.blockstyler.Group group;// Block type: Group
  private nxopen.blockstyler.DoubleBlock expectationV1X;// Block type: Double
  private nxopen.blockstyler.DoubleBlock expectationV1Y;// Block type: Double
  private nxopen.blockstyler.DoubleBlock expectationV1Z;// Block type: Double
  private nxopen.blockstyler.Group group1;// Block type: Group
  private nxopen.blockstyler.DoubleBlock varianceV1X;// Block type: Double
  private nxopen.blockstyler.DoubleBlock varianceV1Y;// Block type: Double
  private nxopen.blockstyler.DoubleBlock varianceV1Z;// Block type: Double
  private nxopen.blockstyler.Group group2;// Block type: Group
  private nxopen.blockstyler.IntegerBlock sampleNumberV1;// Block type: Integer
  private nxopen.blockstyler.Group group3;// Block type: Group
  private nxopen.blockstyler.DoubleBlock expectationV2X;// Block type: Double
  private nxopen.blockstyler.DoubleBlock expectationV2Y;// Block type: Double
  private nxopen.blockstyler.DoubleBlock expectationV2Z;// Block type: Double
  private nxopen.blockstyler.Group group11;// Block type: Group
  private nxopen.blockstyler.DoubleBlock varianceV2X;// Block type: Double
  private nxopen.blockstyler.DoubleBlock varianceV2Y;// Block type: Double
  private nxopen.blockstyler.DoubleBlock varianceV2Z;// Block type: Double
  private nxopen.blockstyler.Group group21;// Block type: Group
  private nxopen.blockstyler.IntegerBlock sampleNumberV2;// Block type: Integer
  
  //------------------------------------------------------------------------------
  //Constructor for NX Styler class
  //------------------------------------------------------------------------------
  public NormalDistributedLine() throws Exception, RemoteException
  {
      try
      {
          theSession = (Session)SessionFactory.get("Session");
          theUI = (UI)SessionFactory.get("UI");
          theDlxFileName = "NormalDistributedLine.dlx";
          theDialog = theUI.createDialog(theDlxFileName);
          theDialog.addOkHandler(this);
          theDialog.addUpdateHandler(this);
          theDialog.addInitializeHandler(this);
          theDialog.addDialogShownHandler(this);
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          throw new Exception(ex);
      }
  }
  //------------------------------- DIALOG LAUNCHING ---------------------------------
  //
  //    Before invoking this application one needs to open any part/empty part in NX
  //    because of the behavior of the blocks.
  //
  //    Make sure the dlx file is in one of the following locations:
  //        1.) From where NX session is launched
  //        2.) $UGII_USER_DIR/application
  //        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
  //            recommended. This variable is set to a full directory path to a file 
  //            containing a list of root directories for all custom applications.
  //            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
  //
  //    You can create the dialog using one of the following way:
  //
  //    1. USER EXIT
  //
  //        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
  //        2) Invoke the Shared Library through File->Execute->NX Open menu.
  //
  //------------------------------------------------------------------------------
  public static void main(String [] argv) throws Exception
  {
      NormalDistributedLine theNormalDistributedLine = null;
      try
      {
          theNormalDistributedLine = new NormalDistributedLine();
          // The following method shows the dialog immediately
          theNormalDistributedLine.show();
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
      finally
      {
          if(theNormalDistributedLine != null)
          {
              theNormalDistributedLine.dispose();
              theNormalDistributedLine = null;
          }
      }
  }
  
  //------------------------------------------------------------------------------
  // This method specifies how a shared image is unloaded from memory
  // within NX. This method gives you the capability to unload an
  // internal NX Open application or user  exit from NX. Specify any
  // one of the three constants as a return value to determine the type
  // of unload to perform:
  //
  //
  //    Immediately : unload the library as soon as the automation program has completed
  //    Explicitly  : unload the library from the "Unload Shared Image" dialog
  //    AtTermination : unload the library when the NX session terminates
  //
  //
  // NOTE:  A program which associates NX Open applications with the menubar
  // MUST NOT use this option since it will UNLOAD your NX Open application image
  // from the menubar.
  //------------------------------------------------------------------------------
   public static final int getUnloadOption()
  {
      //return BaseSession.LibraryUnloadOption.EXPLICITLY;
       return BaseSession.LibraryUnloadOption.IMMEDIATELY;
      // return BaseSession.LibraryUnloadOption.AT_TERMINATION;
  }
  
  //------------------------------------------------------------------------------
  // Following method cleanup any housekeeping chores that may be needed.
  // This method is automatically called by NX.
  //------------------------------------------------------------------------------
  public static void onUnload() throws NXException, RemoteException
  {
      try
      {
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
  }
  
  //------------------------------------------------------------------------------
  //This method shows the dialog on the screen
  //------------------------------------------------------------------------------
  public int show() throws NXException, RemoteException
  {
      try
      {
          theDialog.show();
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
      return 0;
  }
  
  //------------------------------------------------------------------------------
  //Method Name: dispose
  //------------------------------------------------------------------------------
  public void dispose() throws NXException, RemoteException
  {
      if(theDialog != null)
      {
          theDialog.dispose();
          theDialog = null;
      }
  }
  
  //------------------------------------------------------------------------------
  //---------------------Block UI Styler Callback Functions--------------------------
  //------------------------------------------------------------------------------
  
  //------------------------------------------------------------------------------
  //Callback Name: initialize
  //------------------------------------------------------------------------------
  public void initialize() throws NXException, RemoteException
  {
      try
      {
          group = (nxopen.blockstyler.Group)theDialog.topBlock().findBlock("group");
          expectationV1X = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("expectationV1X");
          expectationV1Y = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("expectationV1Y");
          expectationV1Z = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("expectationV1Z");
          group1 = (nxopen.blockstyler.Group)theDialog.topBlock().findBlock("group1");
          varianceV1X = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("varianceV1X");
          varianceV1Y = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("varianceV1Y");
          varianceV1Z = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("varianceV1Z");
          group2 = (nxopen.blockstyler.Group)theDialog.topBlock().findBlock("group2");
          sampleNumberV1 = (nxopen.blockstyler.IntegerBlock)theDialog.topBlock().findBlock("sampleNumberV1");
          group3 = (nxopen.blockstyler.Group)theDialog.topBlock().findBlock("group3");
          expectationV2X = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("expectationV2X");
          expectationV2Y = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("expectationV2Y");
          expectationV2Z = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("expectationV2Z");
          group11 = (nxopen.blockstyler.Group)theDialog.topBlock().findBlock("group11");
          varianceV2X = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("varianceV2X");
          varianceV2Y = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("varianceV2Y");
          varianceV2Z = (nxopen.blockstyler.DoubleBlock)theDialog.topBlock().findBlock("varianceV2Z");
          group21 = (nxopen.blockstyler.Group)theDialog.topBlock().findBlock("group21");
          sampleNumberV2 = (nxopen.blockstyler.IntegerBlock)theDialog.topBlock().findBlock("sampleNumberV2");
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
  }
  
  //------------------------------------------------------------------------------
  //Callback Name: dialogShown
  //This callback is executed just before the dialog launch. Thus any value set 
  //here will take precedence and dialog will be launched showing that value. 
  //------------------------------------------------------------------------------
  public void dialogShown() throws NXException, RemoteException
  {
      try
      {
      	String filepath = "C:/Users/max/desktop/PELOPS/LineArrayExchange.txt";
      	LineArray2File file2array = new LineArray2File();
      	 double [][] myDefaultValues = file2array.readFile2Array(filepath);
  		//Vertex 1
			expectationV1X.setValue(myDefaultValues[0][1]);
			expectationV1Y.setValue(myDefaultValues[0][2]);
			expectationV1Z.setValue(myDefaultValues[0][3]);
			
			varianceV1X.setValue(myDefaultValues[0][4]);
			varianceV1Y.setValue(myDefaultValues[0][5]);
			varianceV1Z.setValue(myDefaultValues[0][6]);
			
			//Vertex 2
			expectationV2X.setValue(myDefaultValues[0][7]);
			expectationV2Y.setValue(myDefaultValues[0][8]);
			expectationV2Z.setValue(myDefaultValues[0][9]);
			
			varianceV2X.setValue(myDefaultValues[0][10]);
			varianceV2Y.setValue(myDefaultValues[0][11]);
			varianceV2Z.setValue(myDefaultValues[0][12]);
			
			
//			Rounds the number of sample			
			int roundedSampleNumber = Math.round(100/myDefaultValues.length);
			
			sampleNumberV1.setValue(roundedSampleNumber);
			sampleNumberV2.setValue(roundedSampleNumber);
			
			file2array.removeFirstLineFromFile(filepath);
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
  }
  //------------------------------------------------------------------------------
  //Callback Name: update
  //Following callback is associated with the "theDialog" Block.
  //------------------------------------------------------------------------------
  public int update( nxopen.blockstyler.UIBlock block) throws NXException, RemoteException
  {
      try
      {
          if(block == expectationV1X)
          {
          //---------Enter your code here-----------
          }
          else if(block == expectationV1Y)
          {
          //---------Enter your code here-----------
          }
          else if(block == expectationV1Z)
          {
          //---------Enter your code here-----------
          }
          else if(block == varianceV1X)
          {
          //---------Enter your code here-----------
          }
          else if(block == varianceV1Y)
          {
          //---------Enter your code here-----------
          }
          else if(block == varianceV1Z)
          {
          //---------Enter your code here-----------
          }
          else if(block == sampleNumberV1)
          {
          //---------Enter your code here-----------
          }
          else if(block == expectationV2X)
          {
          //---------Enter your code here-----------
          }
          else if(block == expectationV2Y)
          {
          //---------Enter your code here-----------
          }
          else if(block == expectationV2Z)
          {
          //---------Enter your code here-----------
          }
          else if(block == varianceV2X)
          {
          //---------Enter your code here-----------
          }
          else if(block == varianceV2Y)
          {
          //---------Enter your code here-----------
          }
          else if(block == varianceV2Z)
          {
          //---------Enter your code here-----------
          }
          else if(block == sampleNumberV2)
          {
          //---------Enter your code here-----------
          }
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
      return 0;
  }
  
  //------------------------------------------------------------------------------
  //Callback Name: ok
  //------------------------------------------------------------------------------
  public int ok() throws NXException, RemoteException
  {
      int errorCode = 0;
      try
      {
      	LinkedUDO.udoselected = 1;
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          errorCode = 1;
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
      return errorCode;
  }
  
  //------------------------------------------------------------------------------
  //Function Name: GetBlockProperties
  //------------------------------------------------------------------------------
  public PropertyList getBlockProperties(String blockID) throws NXException, RemoteException
  {
      PropertyList plist = null;
      try
      {
          plist = theDialog.getBlockProperties(blockID);
      }
      catch(Exception ex)
      {
          //---- Enter your exception handling code here -----
          theUI.nxmessageBox().show("Block Styler", nxopen.NXMessageBox.DialogType.ERROR, ex.getMessage());
      }
      return plist;
  }
  
}
